data_dir: "lightning/downstream/sound_classification/_data/TAU2019UAS"
name: TAU2019UAS
parser: "plain"
unit_name: "mfcc-64c"
n_symbols: 64
subsets:
  test: test.json
  train: train.json
  val: val.json
