name: "LJSpeech"
parser: "nest-sf"
lang_id: "en"
unit_name: hubert--en1-512c-l9
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/LJSpeech"

subsets:
    train: "train.json"
    val: "test.json"
    test: "test.json"

text_cleaners: ["english_cleaners"]
