name: "LibriTTS"
lang_id: "en"
unit_name: hubert--en2-512c-l9
n_symbols: 512

data_dir: "_data/LibriTTS"

subsets:
    train: "train.txt"
    val: "val.txt"
    test: "test.txt"

text_cleaners: ["english_cleaners"]
