name: "LibriTTS"
parser: "nest-sf"
lang_id: "en"
unit_name: hubert--en2-512c-l9
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/LibriTTS"

subsets:
    train: "train.json"
    val: "val.json"
    test: "test.json"

text_cleaners: ["english_cleaners"]
