data_dir: _data/AISHELL-3
lang_id: zh
name: AISHELL-3
subsets:
  test: dataset_config/AISHELL-3/split/test.json
  train: dataset_config/AISHELL-3/split/train.json
  val: dataset_config/AISHELL-3/split/val.json
text_cleaners:
- transliteration_cleaners
