name: "M-AILABS/fr_FR"
lang_id: "fr"
unit_name: hubert--fr2-512c-l9
n_symbols: 512

data_dir: "_data/M-AILABS/fr_FR"

subsets:
    train: "train.txt"
    val: "test.txt"
    test: "test.txt"

text_cleaners: ["basic_cleaners"]
