name: "M-AILABS/ru_RU"
parser: "nest-sf"
lang_id: "ru"
unit_name: mfcc-512c
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/M-AILABS/ru_RU"

subsets:
    train: "train.json"
    val: "test.json"
    test: "test.json"

text_cleaners: ["basic_cleaners"]
