train_config:
  scheduler_type: const
  optimizer:
    lr: 0.00005
    batch_size: 4
    betas: [0.9, 0.98]
    eps: 0.000000001
    weight_decay: 0.0
    grad_clip_thresh: 1.0
    grad_acc_step: 4
  step:
    max_epochs: 6
    log_step: 1000
saver_names:
- mtl-pr
algorithm_config:
  freeze_core: "cnn"
