name: "kss"
parser: "nest-sf"
lang_id: "ko"
unit_name: mfcc-512c
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/kss"

subsets:
    train: "train.json"
    val: "test.json"
    test: "test.json"

text_cleaners: ["transliteration_cleaners"]
