name: "kss"
parser: "nest-sf"
lang_id: "ko"
unit_name: hubert--ko-512c-l9
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/kss"

subsets:
    train: "train.txt"
    val: "test.txt"
    test: "test.txt"

text_cleaners: ["transliteration_cleaners"]
