name: "AISHELL-3"
parser: "nest-sf"
lang_id: "zh"
unit_name: hubert--zh2-512c-l9
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/AISHELL-3"

subsets:
    train: "train.txt"
    val: "test.txt"
    test: "test.txt"

text_cleaners: ["transliteration_cleaners"]
