scheduler_type: const
optimizer:
  lr: 0.0005
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
step:
  total_step: 100000
  log_step: 500
  val_step: 5000
  save_step: 20000
