name: "CSMSC"
lang_id: "zh"
unit_name: hubert--zh1-512c
n_symbols: 512

data_dir: "_data/CSMSC"

subsets:
    train: "train.txt"
    val: "test.txt"
    test: "test.txt"

text_cleaners: ["transliteration_cleaners"]
