name: "JSUT"
parser: "nest-sf"
lang_id: "jp"
unit_name: hubert--jp-512c-l9
n_symbols: 512

data_dir: "lightning/downstream/phoneme_recognition/_data/JSUT"

subsets:
    train: "train.json"
    val: "test.json"
    test: "test.json"

text_cleaners: ["transliteration_cleaners"]
