name: "JSUT"
lang_id: "jp"
unit_name: hubert--jp-512c-l9
n_symbols: 512

data_dir: "_data/JSUT"

subsets:
    train: "train.txt"
    val: "test.txt"
    test: "test.txt"

text_cleaners: ["transliteration_cleaners"]
